services:
  flipt:
    image: docker.flipt.io/flipt/flipt:v2
    ports:
      - '8080:8080'
      - '9000:9000'
    volumes:
      - ./config.yaml:/etc/flipt/config/default.yml:ro
      - flipt_data:/var/opt/flipt
    environment:
      - FLIPT_CORS_ENABLED=true
      - FLIPT_CORS_ALLOWED_ORIGINS=http://localhost:3333

volumes:
  flipt_data: {}
